/* ══════════════════════════════════════════════════════════════════
   POST DESIGN SYSTEM — Dynamic CSS post templates

   Templates define STRUCTURE (layout, text position, overlay type).
   AI generates VARIATIONS per run (colors, filter intensity, accent
   positions, gradient angles) so every post is unique but on-brand.
   ══════════════════════════════════════════════════════════════════ */

/* ── Dynamic style overrides generated by AI per run ── */
export interface StyleVariation {
  accentColor: string;        // hex, e.g. "#7ab82e"
  gradientAngle: number;      // 0-360
  filterContrast: number;     // 0.9-1.4
  filterSaturate: number;     // 0.8-1.5
  filterBrightness: number;   // 0.7-1.2
  filterSepia: number;        // 0-0.2
  overlayOpacity: number;     // 0.3-0.9
  headlineColor: string;      // hex
  sublineColor: string;       // hex with alpha
  vignetteStrength: number;   // 0-0.7
  accentWidth: number;        // 8-48 px
  borderRadius: number;       // 0-24 px for overlay shapes
}

export const DEFAULT_VARIATION: StyleVariation = {
  accentColor: "#7ab82e",
  gradientAngle: 180,
  filterContrast: 1.1,
  filterSaturate: 1.15,
  filterBrightness: 0.95,
  filterSepia: 0,
  overlayOpacity: 0.8,
  headlineColor: "#ffffff",
  sublineColor: "rgba(255,255,255,0.6)",
  vignetteStrength: 0.4,
  accentWidth: 40,
  borderRadius: 0,
};

/* ── Template structure ── */
export interface PostTemplate {
  id: string;
  name: string;
  category: "premium" | "bold" | "minimal" | "editorial" | "promo" | "engagement" | "storytelling" | "showcase";
  preview: string;
  layout: LayoutType;
}

export type LayoutType =
  | "bottom-gradient"    // gradient bottom, text in lower third
  | "center-hero"       // dark overlay, huge centered text
  | "top-headline"      // text at top, photo below
  | "side-panel"        // solid panel on left/right, photo on other side
  | "bottom-bar"        // solid bar at bottom
  | "frosted-center"    // frosted glass card centered
  | "diagonal-split"    // diagonal division
  | "frame-inset"       // thin border frame inset
  | "fullbleed-subtle"  // very subtle overlay, text at bottom
  | "top-bar"           // solid bar at top
  | "dual-tone"         // two-tone split background
  | "vignette-focus"    // heavy vignette, text in center
  | "banner-stripe"     // horizontal stripe across middle
  | "corner-card"       // small card in a corner
  | "floating-pill"     // pill-shaped text container floating
  | "magazine-grid"     // editorial grid lines
  | "gradient-sweep"    // angled gradient sweep across
  | "spotlight-circle"  // circular spotlight effect
  | "bottom-wave"       // wavy bottom overlay
  | "minimal-caption"   // barely any overlay, just tiny caption
  | "text-block"        // solid text block floating
  | "cinematic-bars"    // letterbox black bars top/bottom
  | "split-vertical";   // vertical 50/50 split

export const POST_TEMPLATES: PostTemplate[] = [
  // ═══ PREMIUM ═══
  { id: "cinematic-gold", name: "Cinematic Gold", category: "premium", preview: "linear-gradient(135deg, #7ab82e, #0a0a0f)", layout: "bottom-gradient" },
  { id: "warm-editorial", name: "Warm Editorial", category: "premium", preview: "linear-gradient(135deg, #e8a87c, #1a1210)", layout: "frame-inset" },
  { id: "dark-luxury", name: "Dark Luxury", category: "premium", preview: "linear-gradient(135deg, #8fd440, #12121a)", layout: "bottom-gradient" },

  // ═══ BOLD ═══
  { id: "bold-center", name: "Bold Center", category: "bold", preview: "linear-gradient(135deg, #fff, #111)", layout: "center-hero" },
  { id: "bold-diagonal", name: "Bold Diagonal", category: "bold", preview: "linear-gradient(135deg, #ff6b35, #111)", layout: "diagonal-split" },
  { id: "bold-statement", name: "Bold Statement", category: "bold", preview: "linear-gradient(135deg, #fbbf24, #111)", layout: "cinematic-bars" },

  // ═══ MINIMAL ═══
  { id: "clean-bar", name: "Clean Bar", category: "minimal", preview: "linear-gradient(135deg, #f8f8f8, #888)", layout: "bottom-bar" },
  { id: "clean-side", name: "Clean Side", category: "minimal", preview: "linear-gradient(135deg, #e8e8e8, #555)", layout: "side-panel" },
  { id: "whisper", name: "Whisper", category: "minimal", preview: "linear-gradient(135deg, #ddd, #999)", layout: "minimal-caption" },

  // ═══ EDITORIAL ═══
  { id: "magazine-cover", name: "Magazine Cover", category: "editorial", preview: "linear-gradient(135deg, #2d5a27, #0a0a0f)", layout: "top-headline" },
  { id: "photo-journal", name: "Photo Journal", category: "editorial", preview: "linear-gradient(135deg, #a0876c, #1a1a1a)", layout: "fullbleed-subtle" },
  { id: "editorial-grid", name: "Editorial Grid", category: "editorial", preview: "linear-gradient(135deg, #666, #111)", layout: "magazine-grid" },

  // ═══ PROMO ═══
  { id: "promo-banner", name: "Promo Banner", category: "promo", preview: "linear-gradient(135deg, #7ab82e, #2a1a00)", layout: "bottom-bar" },
  { id: "promo-split", name: "Promo Split", category: "promo", preview: "linear-gradient(135deg, #22c55e, #0a0a0f)", layout: "split-vertical" },
  { id: "promo-stripe", name: "Promo Stripe", category: "promo", preview: "linear-gradient(135deg, #e11d48, #0a0a0f)", layout: "banner-stripe" },

  // ═══ ENGAGEMENT ═══
  { id: "question-frosted", name: "Question Frosted", category: "engagement", preview: "linear-gradient(135deg, #3b82f6, #0a0a0f)", layout: "frosted-center" },
  { id: "engagement-pop", name: "Engagement Pop", category: "engagement", preview: "linear-gradient(135deg, #f59e0b, #0a0a0f)", layout: "bottom-gradient" },
  { id: "poll-card", name: "Poll Card", category: "engagement", preview: "linear-gradient(135deg, #8b5cf6, #0a0a0f)", layout: "floating-pill" },

  // ═══ STORYTELLING ═══
  { id: "story-spotlight", name: "Story Spotlight", category: "storytelling", preview: "linear-gradient(135deg, #0ea5e9, #0a0a0f)", layout: "spotlight-circle" },
  { id: "story-vignette", name: "Story Vignette", category: "storytelling", preview: "linear-gradient(135deg, #78350f, #0a0a0f)", layout: "vignette-focus" },
  { id: "story-cinematic", name: "Story Cinematic", category: "storytelling", preview: "linear-gradient(135deg, #1e293b, #0a0a0f)", layout: "cinematic-bars" },

  // ═══ SHOWCASE ═══
  { id: "project-card", name: "Project Card", category: "showcase", preview: "linear-gradient(135deg, #059669, #0a0a0f)", layout: "corner-card" },
  { id: "showcase-sweep", name: "Showcase Sweep", category: "showcase", preview: "linear-gradient(135deg, #7c3aed, #0a0a0f)", layout: "gradient-sweep" },
];

export function getTemplateById(id: string): PostTemplate | undefined {
  return POST_TEMPLATES.find((t) => t.id === id);
}

export function getRandomVariation(baseAccent?: string): StyleVariation {
  const accents = ["#7ab82e", "#4d6340", "#3c4a30", "#795220", "#a07a40", "#8fd440", "#22c55e", "#059669", "#0ea5e9", "#e3e3d2"];
  const accent = baseAccent || accents[Math.floor(Math.random() * accents.length)];

  return {
    accentColor: accent,
    gradientAngle: 150 + Math.floor(Math.random() * 60),
    filterContrast: 1 + Math.random() * 0.3,
    filterSaturate: 0.9 + Math.random() * 0.5,
    filterBrightness: 0.8 + Math.random() * 0.3,
    filterSepia: Math.random() * 0.12,
    overlayOpacity: 0.5 + Math.random() * 0.35,
    headlineColor: "#ffffff",
    sublineColor: `rgba(255,255,255,${(0.5 + Math.random() * 0.3).toFixed(2)})`,
    vignetteStrength: 0.2 + Math.random() * 0.4,
    accentWidth: 20 + Math.floor(Math.random() * 28),
    borderRadius: Math.floor(Math.random() * 20),
  };
}
